name: Build environment and Run Unit Test

on:
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Run Unit Test
        run: go test -v ./...